// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQhaDxYs99MjJK1KmFOPwIhELdc7H2KSI',
    appId: '1:693678915726:web:03a19cc3436bd33fe2c9df',
    messagingSenderId: '693678915726',
    projectId: 'soywarmi-e1add',
    authDomain: 'soywarmi-e1add.firebaseapp.com',
    storageBucket: 'soywarmi-e1add.appspot.com',
    measurementId: 'G-J5BMRLLL42',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8h9Lb1Y8MmRkZr0Rlu7HCbvvwtQCwCMo',
    appId: '1:693678915726:android:7946a2dfa34ff189e2c9df',
    messagingSenderId: '693678915726',
    projectId: 'soywarmi-e1add',
    storageBucket: 'soywarmi-e1add.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr_4ZTwbWF968b7O3MvXtvSaFkOmD3bn8',
    appId: '1:693678915726:ios:0b35df996191490be2c9df',
    messagingSenderId: '693678915726',
    projectId: 'soywarmi-e1add',
    storageBucket: 'soywarmi-e1add.appspot.com',
    androidClientId: '693678915726-igddenuua75rq1m3cuirr8gk36m3g6jb.apps.googleusercontent.com',
    iosClientId: '693678915726-luga2a86b2jaj1k8uq91u7s9m5kdbfs9.apps.googleusercontent.com',
    iosBundleId: 'com.example.soywarmiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr_4ZTwbWF968b7O3MvXtvSaFkOmD3bn8',
    appId: '1:693678915726:ios:c2e5e565fc689f0ce2c9df',
    messagingSenderId: '693678915726',
    projectId: 'soywarmi-e1add',
    storageBucket: 'soywarmi-e1add.appspot.com',
    androidClientId: '693678915726-igddenuua75rq1m3cuirr8gk36m3g6jb.apps.googleusercontent.com',
    iosClientId: '693678915726-lnlq2f8fssgfmh4ms4h87sh5g89kpkbj.apps.googleusercontent.com',
    iosBundleId: 'com.example.soywarmiApp.RunnerTests',
  );
}
