name: Build android APK

on:
  push:
    branches:
      - develop
      
jobs: 
  build:
    name: Pre-release
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v2
        with:
          java-version: 'zulu'
          distribution: '17'
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.0"
          channel: 'stable'

      - run: flutter pub get
        name: Downloading packages

      - run: flutter build apk --release --split-per-abi
        name: Building apk

      - name: Get commit ID
        id: get_commit_id
        run: echo ::set-output name=commit_id::$(git rev-parse --short HEAD)

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with: 
          artifacts: "build/app/outputs/apk/release/*"
          tag: ${{ steps.get_commit_id.outputs.commit_id }}
          token: ${{ secrets.APP_TOKEN }}
          prerelease: true

