name: Ci
on: 
  pull_request:
    branches:
      - develop

jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 'zulu'
          distribution: '17'
      - uses: subosito/flutter-action@v2
        with: 
          channel: 'stable'
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test




